version: '3.9'

services:

  broker1:
    build: ./broker
    container_name: broker1

    command:
      [
        "./broker",
        "8000",
        "8001",
        "8002"
      ]

    ports:
      - "8000:8000"

    restart: unless-stopped

  drone1:
    build: ./drone

    environment:
      - BROKERS=x.x.x.1:8000,x.x.x.2:8001,x.x.x.3:8002

    depends_on:
      - broker1

    restart: unless-stopped

  recurso_b1:
    build: ./recurso

    command:
      [
        "./recurso",
        "x.x.x.1:8000"
      ]

    depends_on:
      - broker1

    restart: unless-stopped

  servico_b1:
    build: ./servico

    command:
      [
        "./servico",
        "x.x.x.1:8000"
      ]

    depends_on:
      - broker1

    restart: unless-stopped